import { selectorRules } from "./rule-utils.ts";
import { archivesStyles } from "./rules/archives.ts";
import { articleStyles } from "./rules/article.ts";
import { categoriesStyles } from "./rules/categories.ts";
import { commonStyles } from "./rules/common.ts";
import { linksStyles } from "./rules/links.ts";
import { tagsStyles } from "./rules/tags.ts";
import { wordsStyles } from "./rules/words.ts";

export const styleFeatures = {
    common: { sources: ["base.css", "motion.css"], suffix: "", styles: commonStyles },
    article: { sources: [], suffix: "-article", styles: articleStyles },
    archives: { sources: [], suffix: "-archives", styles: archivesStyles },
    categories: { sources: [], suffix: "-categories", styles: categoriesStyles },
    links: { sources: [], suffix: "-links", styles: linksStyles },
    tags: { sources: [], suffix: "-tags", styles: tagsStyles },
    words: { sources: [], suffix: "-words", styles: wordsStyles },
} as const;

export type StyleFeature = keyof typeof styleFeatures;

export const componentRules = Object.entries(styleFeatures).flatMap(([feature, { styles }]) =>
    selectorRules(feature, styles),
);

export function featureStateClasses(feature: StyleFeature): string[] {
    return styleFeatures[feature].styles.map((_, index) => `stalux-style-${feature}-${index}`);
}

/** Native integrations retain selectors generated by Markdown and third-party engines. */
export const nativeFeatures = [
    { sources: ["content.css", "math.css"], suffix: "-prose" },
    { sources: ["integrations.css"], suffix: "-waline" },
] as const;
