import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse as parseAstro } from "@astrojs/compiler";
import { generate, ident, parse, walk } from "css-tree";

const root = path.resolve(import.meta.dirname, "../src");
const classes = new Set<string>();
const variables = new Set<string>();
const animations = new Set<string>();
const aliases = new Set([
    "a-none",
    "agent-home-summary",
    "agent-recovery",
    "bg-layer",
    "bg-a",
    "bg-b",
    "nav-icon",
    "badge-group",
    "date-time",
    "home-btn",
    "postLayout",
    "stagger-children",
    "random-post-item",
    "random-post-link",
]);
const publicVariables = new Set([
    "--font-body",
    "--font-code",
    "--waline-accent-rgb",
    "--accent",
    "--foreground-60p",
]);
function collectCss(css: string) {
    walk(parse(css, { parseCustomProperty: true }), (node) => {
        if (node.type === "ClassSelector") {
            const name = ident.decode(node.name);
            if (name.startsWith("stalux-") || aliases.has(name)) classes.add(name);
        }
        if (
            node.type === "Declaration" &&
            node.property.startsWith("--") &&
            !publicVariables.has(node.property) &&
            !node.property.startsWith("--waline-") &&
            !node.property.startsWith("--astro-")
        )
            variables.add(node.property);
        if (
            node.type === "Identifier" &&
            node.name.startsWith("--") &&
            !publicVariables.has(node.name) &&
            !/^--(?:waline|astro|ec|pswp)-/u.test(node.name)
        )
            variables.add(node.name);
        if (node.type === "Atrule" && node.name === "keyframes" && node.prelude)
            animations.add(generate(node.prelude));
    });
}
function files(dir: string): string[] {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const filename = path.join(dir, entry.name);
        return entry.isDirectory() ? files(filename) : [filename];
    });
}
for (const filename of files(path.join(root, "styles")).filter((file) =>
    /generated.*\.css$/u.test(file),
))
    collectCss(readFileSync(filename, "utf8"));
for (const filename of ["components", "layouts", "pages"]
    .flatMap((dir) => files(path.join(root, dir)))
    .filter((file) => file.endsWith(".astro"))) {
    const { ast } = await parseAstro(readFileSync(filename, "utf8"));
    function visit(node: typeof ast | (typeof ast.children)[number]) {
        if ("attributes" in node)
            for (const attribute of node.attributes) {
                if (attribute.name === "class" && attribute.kind === "quoted")
                    for (const name of attribute.value.split(/\s+/u)) {
                        if (name.startsWith("stalux-") || aliases.has(name)) classes.add(name);
                    }
            }
        if ("name" in node && node.name === "style" && "children" in node)
            collectCss(
                node.children.map((child) => ("value" in child ? child.value : "")).join(""),
            );
        if ("children" in node) for (const child of node.children) visit(child);
    }
    visit(ast);
}
for (const name of aliases) classes.add(name);
for (const name of ["--archive-estimate", "--archive-group-estimate", "--nav-scale"])
    variables.add(name);
function table(names: Set<string>, prefix: string) {
    return Object.fromEntries(
        [...names].sort().map((name, index) => [name, `${prefix}${index.toString(36)}`]),
    );
}
const output = `// Generated by scripts/build-style-names.ts. Production names are version-local.\nexport const styleNames: { classes: Record<string, string>; variables: Record<string, string>; animations: Record<string, string> } = ${JSON.stringify({ classes: table(classes, "s"), variables: table(variables, "--s"), animations: table(animations, "k") }, null, 4)};\n`;
const destination = path.join(root, "internal/style-names.generated.ts");
let previous = "";
try {
    previous = readFileSync(destination, "utf8");
} catch {
    /* First generation. */
}
if (previous !== output) writeFileSync(destination, output);
console.info(
    `[styles] compact mapping: ${classes.size} classes, ${variables.size} variables, ${animations.size} animations`,
);
