/**
 * 字体子集化脚本 — 用 subset-font (harfbuzz WASM) 替代 cn-font-split。
 *
 * 纯 WASM，无 native 依赖，CI 友好。
 * 扫描所有内容文件 → 提取唯一字符 → 生成单个 woff2 子集 → 输出到 public/fonts/。
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

import { globSync } from "glob";
import subsetFont from "subset-font";

const SCAN_GLOBS = [
    "stalux/posts/**/*.md",
    "stalux/about/**/*.md",
    "stalux/words/**/*.md",
    "src/pages/**/*.astro",
    "src/components/**/*.astro",
    "src/layouts/**/*.astro",
    "src/i18n/*.json",
    "config.yml",
];

const FONT_INPUT = "src/assets/fonts/LXGWWenKai-Regular.ttf";
const FONT_OUTPUT = "public/fonts/LXGWWenKai-subset.woff2";
const CSS_OUTPUT = "public/fonts/subset.css";

/** 收集所有内容文件中出现过的唯一字符 */
function collectChars(): string {
    const chars = new Set<string>();
    // 基础 ASCII 可打印字符
    for (let i = 0x20; i <= 0x7e; i++) chars.add(String.fromCodePoint(i));
    // CJK 标点
    [
        0x3000, 0xff0c, 0x3002, 0xff01, 0xff1f, 0xff1b, 0xff1a, 0x201c, 0x201d, 0x3010, 0x3011,
        0x300a, 0x300b, 0xff08, 0xff09, 0x2026, 0x2014, 0xff5e, 0x00b7, 0x3001,
    ].forEach((cp) => chars.add(String.fromCodePoint(cp)));

    for (const pattern of SCAN_GLOBS) {
        for (const f of globSync(pattern, { cwd: process.cwd() })) {
            try {
                for (const ch of readFileSync(f, "utf-8")) {
                    chars.add(ch);
                }
            } catch {
                // 跳过无法读取的文件
            }
        }
    }
    const result = [...chars].join("");
    const cjkCount = [...result].filter((c) => {
        const cp = c.codePointAt(0)!;
        return (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf);
    }).length;
    console.log(
        `[font-subset] Content scan: ${cjkCount} unique CJK chars (${result.length} total) from ${SCAN_GLOBS.length} globs`,
    );
    return result;
}

async function main() {
    const chars = collectChars();
    const fontBuffer = readFileSync(FONT_INPUT);
    console.log(`[font-subset] Input font: ${(fontBuffer.length / 1024 / 1024).toFixed(1)} MB`);

    const subsetBuffer = await subsetFont(fontBuffer, chars, { targetFormat: "woff2" });
    console.log(`[font-subset] Subset size: ${(subsetBuffer.length / 1024).toFixed(1)} KB`);

    mkdirSync(dirname(FONT_OUTPUT), { recursive: true });
    writeFileSync(FONT_OUTPUT, subsetBuffer);
    console.log(`[font-subset] Written: ${FONT_OUTPUT}`);

    // 生成 CSS @font-face（unicode-range 可选，单文件不需要）
    const css = `/* Auto-generated by scripts/font-subset.ts */
@font-face {
    font-family: "LXGW WenKai Subset";
    src: url("/fonts/LXGWWenKai-subset.woff2") format("woff2");
    font-display: swap;
}
`;
    writeFileSync(CSS_OUTPUT, css);
    console.log(`[font-subset] Written: ${CSS_OUTPUT}`);
}

main().catch((e) => {
    console.error("[font-subset] FAILED:", e);
    process.exit(1);
});
