import type { StyleSpec } from "../rule-utils.ts";

export const articleStyles: StyleSpec[] = [
    [".stalux-sidebar .stalux-author-figure", "m-0", {}],
    [".stalux-sidebar .stalux-author-figure figcaption", "text-[1.75rem]", {}],
    [
        ".stalux-sidebar-right #stalux-date-date-time #stalux-date-date",
        "text-[1.5rem] whitespace-nowrap",
        {},
    ],
    [
        ".stalux-sidebar-right #stalux-date-date-time #stalux-date-time",
        "text-[2.25rem] whitespace-nowrap",
        {},
    ],
    [".stalux-random-refresh:hover", "", { color: "var(--accent-60p, #0066cc)" }],
    [".stalux-random-refresh:active", "opacity-[0.7]", {}],
    [".stalux-random-refresh svg", "w-[1em] h-[1em]", {}],
    [
        ".stalux-random-refresh.stalux-random-rotating svg",
        "",
        { animation: "stalux-random-spin 0.6s linear" },
    ],
    [
        ".stalux-random-loading, .stalux-random-error, .stalux-random-no-more",
        "text-center p-[1em] text-[0.95em]",
        { color: "var(--foreground-60p, #666)" },
    ],
    [
        ".stalux-random-list > li > a",
        "block no-underline p-[0.75em_1em] rounded-[0.375em]",
        {
            background: "transparent",
            color: "var(--foreground-60p, #333)",
            transition: "color 0.2s ease, transform 0.2s ease",
            "overflow-wrap": "anywhere",
        },
    ],
    [".stalux-random-list > li > a:hover", "", { background: "var(--white-05p)" }],
    [".stalux-random-list > li > a:active", "", { background: "var(--white-05p)" }],
    [
        ".stalux-random-header",
        "",
        { "border-bottom-color": "rgb(255 255 255 / 0.1)" },
        "@media (prefers-color-scheme: dark)",
    ],
    [
        ".stalux-random-title",
        "",
        { color: "var(--foreground-60p, #e0e0e0)" },
        "@media (prefers-color-scheme: dark)",
    ],
    [
        ".stalux-random-refresh",
        "",
        { color: "var(--foreground-60p, #e0e0e0)" },
        "@media (prefers-color-scheme: dark)",
    ],
    [
        ".stalux-random-loading, .stalux-random-error, .stalux-random-no-more",
        "",
        { color: "var(--foreground-60p, #b0b0b0)" },
        "@media (prefers-color-scheme: dark)",
    ],
    [
        ".stalux-random-list > li > a",
        "",
        { color: "var(--foreground-60p, #e0e0e0)" },
        "@media (prefers-color-scheme: dark)",
    ],
    [".stalux-toc-item:hover", "", { background: "var(--white-05p)" }],
    [
        ".stalux-toc-item:active, .stalux-toc-item.stalux-toc-active",
        "",
        {
            color: "var(--accent-90p)",
            "background-color": "var(--accent-20p)",
            "border-left-color": "var(--accent-80p)",
            "font-weight": "500",
        },
    ],
    [".stalux-toc-depth-1", "pl-xs", {}],
    [".stalux-toc-depth-2", "pl-lg text-stalux-smaller", {}],
    [".stalux-toc-depth-3", "pl-[2.25rem] text-stalux-tiny", {}],
    [
        ".stalux-toc-depth-4, .stalux-toc-depth-5, .stalux-toc-depth-6",
        "pl-2xl text-[0.75rem] text-ink-60",
        {},
    ],
    [
        ":is( .stalux-post-taxonomy-list, .stalux-post-taxonomy-list-column, .stalux-post-taxonomy-list-wrap )",
        "flex gap-sm",
        {},
    ],
    [".stalux-post-taxonomy-item-column:hover", "", { background: "var(--white-05p)" }],
    [".stalux-post-taxonomy-item-column:active", "", { background: "var(--white-05p)" }],
    [".stalux-post-taxonomy-item-pill:hover", "", { background: "var(--white-05p)" }],
    [".stalux-post-taxonomy-item-pill:active", "", { background: "var(--white-05p)" }],
    [
        ":is(.stalux-sidebar, .stalux-sidebar-right)",
        "flex flex-col sticky h-fit w-full box-border min-w-0 overflow-y-auto top-[20px] max-h-[calc(100vh_-_40px)] gap-lg p-[var(--space-lg)_0]",
        { "scrollbar-width": "none", "-ms-overflow-style": "none" },
    ],
    [":is(.stalux-sidebar, .stalux-sidebar-right)::-webkit-scrollbar", "hidden", {}],

    [
        ":is(.stalux-sidebar, .stalux-sidebar-right), .stalux-sidebar-right",
        "hidden",
        {},
        "@media (max-width: 768px)",
    ],
    [".stalux-pagination-link::before, .stalux-pagination-link::after", "hidden", {}],
    [
        "a.stalux-pagination-link:is(:hover, :focus-visible)",
        "",
        { background: "var(--white-05p)", "outline-color": "var(--accent-50p)" },
    ],
    [
        "a.stalux-pagination-link:focus-visible",
        "",
        { outline: "2px solid var(--stalux-accent-color)", "outline-offset": "3px" },
    ],
    [
        "a.stalux-pagination-prev-post:is(:hover, :focus-visible) .stalux-pagination-arrow",
        "",
        { translate: "-2px 0" },
    ],
    [
        "a.stalux-pagination-next-post:is(:hover, :focus-visible) .stalux-pagination-arrow",
        "",
        { translate: "2px 0" },
    ],
    [
        ".stalux-pagination-link.stalux-pagination-disabled",
        "pointer-events-none opacity-[0.5]",
        { cursor: "not-allowed", background: "var(--black-15p)" },
    ],
    [".stalux-pagination-link.stalux-pagination-prev-post", "text-left ml-xs", {}],
    [".stalux-pagination-link.stalux-pagination-next-post", "text-right justify-end mr-xs", {}],
    [".stalux-pagination", "m-[var(--space-md)_0]", {}, "@media (max-width: 768px)"],
    [".stalux-pagination-inner", "gap-sm", {}, "@media (max-width: 768px)"],
    [
        ".stalux-pagination-link",
        "flex-col items-start justify-center p-[var(--space-sm)_var(--space-md)] min-h-[120px]",
        {},
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-pagination-link.stalux-pagination-next-post",
        "items-end",
        {},
        "@media (max-width: 768px)",
    ],
    [".stalux-pagination-arrow", "", { transform: "scale(0.85)" }, "@media (max-width: 768px)"],
    [".stalux-pagination-label", "text-[0.75rem] mb-xs", {}, "@media (max-width: 768px)"],
    [
        ".stalux-pagination-title",
        "max-w-full text-stalux-small",
        { "white-space": "normal" },
        "@media (max-width: 768px)",
    ],
    [".stalux-pagination", "m-[var(--space-md)_0]", {}, "@media (max-width: 480px)"],
    [".stalux-pagination-inner", "flex-col gap-sm", {}, "@media (max-width: 480px)"],
    [
        ".stalux-pagination-link",
        "w-full items-center justify-start p-[var(--space-sm)_var(--space-md)] min-h-[100px] gap-md",
        { "flex-direction": "row" },
        "@media (max-width: 480px)",
    ],
    [
        ".stalux-pagination-link.stalux-pagination-prev-post, .stalux-pagination-link.stalux-pagination-next-post",
        "items-center text-left ml-[0] mr-[0]",
        {},
        "@media (max-width: 480px)",
    ],
    [
        ".stalux-pagination-link.stalux-pagination-next-post",
        "justify-start",
        {},
        "@media (max-width: 480px)",
    ],
    [".stalux-pagination-title", "", { "white-space": "normal" }, "@media (max-width: 480px)"],
    [".stalux-post-layout > :nth-child(1)", "m-0", {}],
    [".stalux-post-layout > :nth-child(2)", "m-0 min-w-0", {}],
    [".stalux-post-layout > :nth-child(3)", "m-0", {}],
    [":is(.stalux-sidebar, .stalux-sidebar-right)", "hidden", {}, "@media (max-width: 1599px)"],
    [
        ".stalux-post-layout",
        "",
        { "grid-template-columns": "minmax(0, 1fr)", "max-width": "936px" },
        "@media (max-width: 1599px)",
    ],
    [".stalux-post-page", "p-0", {}, "@media (max-width: 768px)"],
    [".stalux-post-layout", "flex flex-col m-0 p-0 gap-[2rem]", {}, "@media (max-width: 768px)"],
    [".stalux-post-layout > :nth-child(2)", "", { order: "1" }, "@media (max-width: 768px)"],
    [".stalux-post-layout > :nth-child(1)", "", { order: "2" }, "@media (max-width: 768px)"],
    [".stalux-post-layout > :nth-child(3)", "", { order: "3" }, "@media (max-width: 768px)"],
    [".stalux-post-layout", "p-0 gap-[1.25rem]", {}, "@media (max-width: 480px)"],
    [".stalux-post-layout", "gap-[2rem]", { "grid-template-columns": "1fr" }, "@media print"],
    [
        ".stalux-post-layout > :nth-child(1), .stalux-post-layout > :nth-child(3)",
        "hidden",
        {},
        "@media print",
    ],
    [
        ".stalux-post-page *",
        "",
        {
            "animation-duration": "0.01ms !important",
            "animation-iteration-count": "1 !important",
            "transition-duration": "0.01ms !important",
        },
        "@media (prefers-reduced-motion: reduce)",
    ],
    [".stalux-post-layout", "gap-[2rem]", {}, "@media (prefers-contrast: more)"],
    [
        ".stalux-post-layout :focus-visible",
        "",
        { outline: "2px solid var(--accent-80p)", "outline-offset": "2px" },
    ],
    [".stalux-post-page-stats span", "inline-flex items-center gap-[0.3rem]", {}],
    ["#stalux-post-vercount_value_page_pv", "font-semibold", { color: "#ffffffb3" }],
    ["#stalux-post-vercount_container_page_pv", "", { transition: "opacity 0.3s ease" }],
    [
        ".stalux-post-source-link:hover, .stalux-post-source-link:focus, .stalux-post-source-link:active",
        "no-underline",
        {
            background: "var(--accent, #ffffff22)",
            "border-top-color": "var(--accent, #ffffff44)",
            "border-right-color": "var(--accent, #ffffff44)",
            "border-left-color": "var(--accent, #ffffff44)",
        },
    ],
    [".stalux-post-source-link::after", "", { display: "none !important" }],
    [".stalux-post-title", "text-[2rem]", {}, "@media (max-width: 1024px)"],
    [".stalux-post-metadata", "gap-[1rem]", {}, "@media (max-width: 1024px)"],
    [
        ".stalux-article",
        "m-0 box-border w-full p-[clamp(1rem,_2vw,_2rem)]",
        { background: "transparent", "box-shadow": "none" },
        "@media (max-width: 768px)",
    ],
    [".stalux-post-body", "m-0 w-full p-[0_0_2rem]", {}, "@media (max-width: 768px)"],
    [".stalux-post-article-header", "mb-[2rem] p-[1rem_1rem_0]", {}, "@media (max-width: 768px)"],
    [".stalux-post-title", "text-[1.75rem]", {}, "@media (max-width: 768px)"],
    [
        ".stalux-post-metadata",
        "flex-col gap-[0.75rem] text-[0.85rem]",
        {},
        "@media (max-width: 768px)",
    ],
    [".stalux-post-article-footer", "mt-[2rem] pt-[1.5rem]", {}, "@media (max-width: 768px)"],
    [
        ".stalux-post-page-stats",
        "text-[0.85rem] mt-[0.8rem] pt-[0.6rem]",
        {},
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-license-author, .stalux-license-url, .stalux-license-license",
        "m-[var(--space-sm)_0] leading-[1.6] text-stalux-small text-ink-80",
        {},
    ],
    [
        ".stalux-license-box a",
        "relative no-underline pb-[1px]",
        {
            color: "var(--accent-90p)",
            transition:
                "color var(--transition-normal), border-bottom-color var(--transition-normal)",
            "border-bottom": "1px dashed var(--accent-50p)",
        },
    ],
    [
        ".stalux-license-box a:hover",
        "",
        { color: "var(--stalux-accent-color)", "border-bottom-color": "var(--accent-80p)" },
    ],
    [".stalux-license-box a:active", "", { color: "var(--accent-70p)" }],
    [".stalux-license-box:hover .stalux-license-watermark", "opacity-[0.25]", {}],
    [".stalux-license-icon svg", "block h-full w-full", {}],
    [".stalux-license-icon path", "text-ink-full", { fill: "currentColor" }],
    [
        ".stalux-license-box",
        "max-w-[95%] p-md m-[var(--space-md)_auto]",
        {},
        "@media (max-width: 768px)",
    ],
    [".stalux-license-title", "mb-xs text-stalux-base", {}, "@media (max-width: 768px)"],
    [
        ".stalux-license-author, .stalux-license-url, .stalux-license-license",
        "m-[var(--space-xs)_0] text-[0.85rem]",
        {},
        "@media (max-width: 768px)",
    ],
    [".stalux-license-icon", "w-[80px] h-[80px]", {}, "@media (max-width: 768px)"],
    [
        ".stalux-license-box",
        "max-w-full p-sm m-[var(--space-md)_0]",
        {},
        "@media (max-width: 480px)",
    ],
    [".stalux-license-title", "mb-2xs text-stalux-small", {}, "@media (max-width: 480px)"],
    [
        ".stalux-license-author, .stalux-license-url, .stalux-license-license",
        "m-[var(--space-2xs)_0] text-[0.8rem]",
        {},
        "@media (max-width: 480px)",
    ],
    [".stalux-license-icon", "w-[60px] h-[60px]", {}, "@media (max-width: 480px)"],
];
