import type { StyleSpec } from "../rule-utils.ts";

export const commonStyles: StyleSpec[] = [
    ["#stalux-home-show-post-list", "cursor-pointer mt-[3em] text-[1.5em] stalux-glow", {}],
    [
        ".stalux-home-body",
        "box-border w-full h-[auto] p-[2rem_0.5rem_1.5rem_0.5rem] max-w-[95vw]",
        {},
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-home-title",
        "text-[2em] mt-[1em]",
        { "word-break": "break-all" },
        "@media (max-width: 768px)",
    ],
    [".stalux-home-navs", "flex-col items-center gap-[0.5em]", {}, "@media (max-width: 768px)"],
    [".stalux-home-navs nav", "w-full", {}, "@media (max-width: 768px)"],
    ["#stalux-home-show-post-list", "mt-[2em] text-[1.1em]", {}, "@media (max-width: 768px)"],
    [".stalux-post-list-container", "w-full h-[auto] m-[5px_0]", {}],
    [
        ".stalux-post-list-container ul",
        "p-0 flex flex-wrap gap-[2rem] m-[3em]",
        { "list-style-type": "none" },
    ],
    [".stalux-post-list-container ul", "m-[1rem]", {}, "@media (max-width: 768px)"],
    [".stalux-post-list-container ul > li", "m-0 min-w-0", { flex: "1 1 min(22rem, 100%)" }],
    [".stalux-card-post-title a", "text-inherit no-underline", {}],
    [".stalux-post-card > a:first-child", "block min-w-0 w-full", {}],
    [
        ".stalux-card-post-cover img",
        "h-full max-w-full w-full object-cover",
        { transition: "transform var(--transition-fast) ease" },
    ],
    [
        ".stalux-post-card:is(:hover, :focus-within) .stalux-card-post-cover img",
        "",
        { transform: "scale(1.05)" },
    ],
    [
        ".stalux-post-card:is(:hover, :focus-within)",
        "",
        { transform: "translateY(-3px)", "box-shadow": "var(--card-box-shadow-hover)" },
    ],
    [
        ".stalux-card-post-date, .stalux-card-post-updated",
        "inline-flex items-center w-[fit-content] gap-[0.35rem] p-[0.28rem_0.6rem] rounded-[10px] text-[0.9rem] leading-[1.1]",
        { color: "#e8f2ff" },
    ],
    [
        ".stalux-card-post-date",
        "",
        { background: "var(--date-bg)", border: "1px solid var(--date-border)", color: "#e8f2ff" },
    ],
    [
        ".stalux-card-post-updated",
        "",
        {
            background: "var(--updated-bg)",
            border: "1px solid var(--updated-border)",
            color: "#fff7de",
        },
    ],
    [".stalux-card-post-tags a", "no-underline", {}],
    [
        ".stalux-card-post-tag:focus, .stalux-card-post-tag:hover",
        "",
        { background: "var(--tag-bg-hover)" },
    ],
    [".stalux-card-post-categories a", "no-underline", {}],
    [
        ".stalux-card-post-category:focus, .stalux-card-post-category:hover",
        "",
        { background: "var(--category-bg-hover)" },
    ],
    [".stalux-social", "mt-[3em]", {}],
    [".stalux-social ul", "m-0 flex flex-wrap justify-center p-0 gap-[1em]", {}],
    [
        ".stalux-social ul li",
        "box-border inline-flex items-center justify-center overflow-hidden rounded-full text-center w-[2.5em] h-[2.5em]",
        { "font-size": "large", "background-color": "var(--white-15p)" },
    ],
    [
        ".stalux-social ul a, .stalux-social ul .stalux-social-icon-container, .stalux-social ul .stalux-social-custom-icon",
        "h-full w-full inline-flex items-center justify-center leading-[1]",
        {},
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li',
        "",
        {
            animation:
                "stalux-social-stalux-social-arrive 280ms cubic-bezier(0.2, 0.8, 0.2, 1) both",
        },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(2)',
        "",
        { "animation-delay": "30ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(3)',
        "",
        { "animation-delay": "60ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(4)',
        "",
        { "animation-delay": "90ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(5)',
        "",
        { "animation-delay": "120ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(6)',
        "",
        { "animation-delay": "150ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li:nth-child(n + 7)',
        "",
        { "animation-delay": "180ms" },
    ],
    [
        '.stalux-social[data-stalux-social-animate="true"] li',
        "",
        { animation: "none" },
        "@media (prefers-reduced-motion: reduce)",
    ],
    ["nav", "max-w-full min-w-0 w-full", {}],
    [".stalux-nav-scroll-btn:hover", "", { background: "transparent" }],
    [".stalux-nav-scroll-btn[data-visible]", "pointer-events-auto opacity-[1]", {}],
    ['.stalux-nav-scroll-btn[data-side="left"]', "left-[4px]", {}],
    ['.stalux-nav-scroll-btn[data-side="right"]', "right-[4px]", {}],
    [".stalux-nav-container:hover .stalux-nav-scroll-btn[data-visible]", "opacity-[1]", {}],
    [
        ".stalux-nav-scroll-btn svg",
        "w-[20px] h-[20px]",
        { stroke: "currentColor", "stroke-width": "2", fill: "none" },
    ],
    [
        ".stalux-nav-link, .stalux-nav-link:visited",
        "flex items-center w-full cursor-pointer text-inherit no-underline p-[0.5rem_0.75rem] gap-[0.5rem] min-h-[44px]",
        { background: "none", border: "none", font: "inherit" },
    ],
    [".stalux-nav-link .nav-icon", "", { stroke: "var(--white-full)" }],
    [
        ".stalux-nav-link:hover .nav-icon, .stalux-nav-link:hover .stalux-nav-text",
        "",
        { stroke: "var(--stalux-accent-color)", color: "var(--stalux-accent-color)" },
    ],
    [".stalux-nav-toggle svg", "w-[32px] h-[32px]", {}],
    ['.stalux-nav-overlay[data-state="show"]', "block pointer-events-auto opacity-[1]", {}],
    [".stalux-nav-list", "gap-[1rem]", {}, "@media (max-width: 1100px)"],
    [".stalux-nav-item", "text-[1em] mr-[0.6em] ml-[0.6em]", {}, "@media (max-width: 1100px)"],
    [".stalux-nav-item", "text-[0.95em] mr-[0.25em] ml-[0.25em]", {}, "@media (max-width: 900px)"],
    [".stalux-nav-list", "gap-[0.5rem]", {}, "@media (max-width: 900px)"],
    [
        ".stalux-nav-toggle",
        "fixed block top-[0.75rem] left-[0.75rem]",
        {},
        "@media (max-width: 600px)",
    ],
    [".stalux-nav-container", "", { overflow: "visible" }, "@media (max-width: 600px)"],
    ["nav", "w-[auto]", {}, "@media (max-width: 600px)"],
    [
        ".stalux-nav-list",
        "pointer-events-none fixed flex-col items-start justify-start overflow-y-auto top-[0] left-[0] right-[auto] w-[min(220px,_calc(100vw_-_1rem))] h-[100vh] gap-[0] p-[0.5rem_1rem_2rem_1rem] z-[1000]",
        {
            background: "var(--black-20p)",
            "backdrop-filter": "blur(20px)",
            transform: "translateX(-100%)",
        },
        "@media (max-width: 600px)",
    ],
    [
        '.stalux-nav-list[data-state="open"]',
        "pointer-events-auto",
        { transform: "translateX(0)" },
        "@media (max-width: 600px)",
    ],
    [
        ".stalux-nav-item",
        "m-0 w-full text-[0.9em]",
        { "flex-shrink": "0", "border-bottom": "1px solid var(--white-10p)" },
        "@media (max-width: 600px)",
    ],
    [".stalux-nav-text", "", { display: "inline" }, "@media (max-width: 600px)"],
    [
        ".stalux-nav-link",
        "w-full p-[0.45rem_0.75rem] min-h-[44px]",
        { "font-size": "inherit" },
        "@media (max-width: 600px)",
    ],
    [".stalux-nav-link .nav-icon", "w-[18px] h-[18px]", {}, "@media (max-width: 600px)"],
    [".stalux-footer", "p-[1.2rem_0] text-[0.8rem]", {}, "@media (max-width: 768px)"],
    [".stalux-footer-content", "gap-[0.6rem] p-[0_0.8rem]", {}, "@media (max-width: 768px)"],
    [".stalux-footer", "p-[1rem_0] text-[0.8rem]", {}, "@media (max-width: 480px)"],
    [".stalux-footer-content", "gap-[0.6rem] p-[0_0.8rem]", {}, "@media (max-width: 480px)"],
    ["#stalux-to-archive-archs", "mt-[2em]", {}],
    ["#stalux-date-date-time", "flex flex-col items-center mt-[2em] stalux-glow text-ink-full", {}],
    ["#stalux-date-date-time #stalux-date-date", "text-[2em] mb-[0.5em]", {}],
    ["#stalux-date-date-time #stalux-date-time", "text-[3em]", {}],
    [".stalux-author-figure", "flex items-center justify-center", {}],
    [
        ".stalux-author-figure img",
        "rounded-full",
        { transition: "transform 1s ease", "box-shadow": "0 0 10px var(--stalux-accent-color)" },
    ],
    [".stalux-author-figure img:hover", "", { transform: "rotate(360deg)" }],
    [
        ".stalux-author-figure figcaption",
        "font-bold ml-[1em] text-[2.5em] stalux-glow text-ink-full",
        {},
    ],
    [".stalux-author-figure-column figcaption", "text-center ml-[0] mt-[0.5em]", {}],
    [
        ".stalux-author",
        "box-border w-full mt-[2em] p-[1em_0.5em] max-w-[95vw]",
        {},
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-author-figure",
        "gap-[0.5em]",
        { "flex-direction": "column !important" },
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-author-figure img",
        "max-w-[20vw] max-h-[20vw]",
        { width: "64px !important", height: "64px !important" },
        "@media (max-width: 768px)",
    ],
    [
        ".stalux-author-figure figcaption",
        "text-center text-[1.5em] ml-[0] mt-[0.5em] max-w-[90vw]",
        { "word-break": "break-all", "overflow-wrap": "break-word", "white-space": "normal" },
        "@media (max-width: 768px)",
    ],
    [
        ".agent-home-summary",
        "absolute overflow-hidden p-0 w-[1px] h-[1px] m-[-1px]",
        { clip: "rect(0, 0, 0, 0)", "white-space": "normal", border: "0" },
    ],
    [".stalux-404-error-content h1", "m-0 font-bold text-[6rem] text-ink-90", {}],
    [".stalux-404-error-content p", "text-[1.5rem] m-[1rem_0_2rem_0] text-ink-70", {}],
    [
        ".stalux-404-countdown-text",
        "",
        {
            "font-size": "0.95rem !important",
            color: "var(--white-50p) !important",
            margin: "-0.5rem 0 1.5rem 0 !important",
        },
    ],
    [
        ".agent-recovery",
        "max-w-[42rem] leading-[1.7]",
        { margin: "0 auto 1.5rem !important", "font-size": "1rem !important" },
    ],
    [".agent-recovery a", "text-inherit", { "text-decoration-line": "underline" }],
    [
        ".stalux-404-home-btn:hover",
        "",
        {
            background: "var(--accent-20p)",
            transform: "translateY(-2px)",
            "box-shadow": "0 4px 12px var(--shadow-dark)",
        },
    ],
    [".stalux-404-error-content h1", "text-[4rem]", {}, "@media (max-width: 768px)"],
    [".stalux-404-error-content p", "text-[1.2rem]", {}, "@media (max-width: 768px)"],
    [".stalux-theme-info span", "m-0", {}],
    [
        ".stalux-theme-info a",
        "no-underline m-[0_0.2em]",
        { color: "rgba(255, 255, 255, 0.8)", transition: "color 0.3s ease" },
    ],
    [".stalux-theme-info a:hover", "no-underline", { color: "rgba(255, 255, 255, 1)" }],
    [".stalux-copyright span", "m-0", {}],
    [
        ".stalux-beian-beian-info a",
        "no-underline text-[0.9rem]",
        { color: "rgba(255, 255, 255, 0.7)", transition: "color 0.3s ease" },
    ],
    [".stalux-beian-beian-info a:hover", "no-underline", { color: "rgba(255, 255, 255, 0.9)" }],
    [
        ".stalux-beian-public-security-beian:hover",
        "no-underline",
        { color: "rgba(255, 255, 255, 0.9)" },
    ],
    [".stalux-beian-public-security-beian img", "inline-block w-[15px] h-[15px]", {}],
    [".stalux-badges-wrapper .stalux-badge", "w-[auto]", {}],
    [".stalux-badge-group-summary:hover", "text-ink-70", {}],
    [".stalux-badge-group-summary::-webkit-details-marker", "hidden", {}],
    [".stalux-badge-group[open] .stalux-badge-group-arrow", "", { transform: "rotate(90deg)" }],
    [
        '.stalux-badge-group[open] .stalux-badge-group-hint[data-hint="collapsed"], .stalux-badge-group:not([open]) .stalux-badge-group-hint[data-hint="expanded"]',
        "hidden",
        {},
    ],
    [".stalux-badges", "gap-[0.3rem]", {}, "@media (max-width: 768px)"],
    [".stalux-badge", "w-[auto]", {}, "@media (max-width: 768px)"],
];
