name: Publish to npm

on:
    workflow_dispatch:
    push:
        tags:
            - "v*.*.*"

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - run: bun install

            - name: Publish with OIDC provenance
              run: |
                  npm config set registry https://registry.npmjs.org
                  npm publish --provenance --access public
